### ISSUE TITLE
Availability of configuration and population files

### ISSUE THREAD

**Issue by ghost** [matsim-eth/baseline_scenario#50]
Are configuration and population (`population.xml`, `population_attributes.xml` and `schedule.xml`) files available for public use? Is it possible to run this simulation without `daily_counts.csv` samples?

Thanks for your help.

**Comment by ghost** [comment]
I just stumbled upon the [wiki](https://github.com/matsim-eth/baseline_scenario/wiki) page and the [repos2.ivt.ethz.ch](https://repos2.ivt.ethz.ch/svn/ivt_studies/trunk/baseline2010/) containing these files seems to be offline. Do you have any other place where we could access these files?

**Comment by tduberne** [comment]
Dear Mahsa,

although this repository and its issue tracker are public, they are linked to work that is internal to our institution. In particular, we are not allowed to distribute the underlying data, which is why it is stored behind a firewall. However, the data should not be difficult to obtain from the relevant federal offices.

If you are interested discussing this in more details, please get in touch with me by [e-mail](mailto:thibautd@ethz.ch).
